### ISSUE TITLE
Emerald Mike

### ISSUE THREAD

**Issue by ghost** [SkylixGH/LuxJS#8]
Btw remmberthe _scripts folder? Well im going to actualy implement a build tool too in luxjs.
fun fact: typescript was coded purly in JS but when ts was released they coded ts in ts.

Basicly thats whats gona happen to luxjs. the build enviorment, compilers, EXE builders and byte code transformers will be built into luxjs to maximize speed

**Comment by NekaouMike** [comment]
Mhm.
And why is the title my name 😐

**Comment by ghost** [comment]
UwU  3.75 is why ur name is there

**Comment by ghost** [comment]
Oh and with this, u can use `luxjs dev` in all ur apps, infact, hye ararat could use luxjs build

so then luxjs will support...
 - NodeJS
 - React Desktop Apps
 - React Mobile Apps
 - React Web Apps
 - Server APIS
 - CLI Apps

**Comment by NekaouMike** [comment]
Mhm

**Comment by ghost** [comment]
**LUXJS CONFIG EXAMPLE**
```ts
// lux.client.ts

import { defineConfig } from "@skylixgh/luxjs-client";

export default defineConfig({
    app: {
        type: "basic"
    }
});
```

Basic - A simple NodeJS console app or server app
Desktop - React desktop app
Mobile - React mobile app

**I plan to change `lux.client.ts` to be `lux.config.ts` idk what do u think**

**Comment by DarkMalwre** [comment]
Interesting

**Comment by samdev-7** [comment]
Interesting

**Comment by ghost** [comment]
Interesting

**Comment by DarkMalwre** [comment]
rly interesting

**Comment by ghost** [comment]
rly rly interesting
